language: ruby
rbenv:
- 2.7.2
addons:
  postgresql: 9.6
script:
- bundle exec rails db:{create,migrate} RAILS_ENV=test
- bundle exec rspec
deploy:
  provider: heroku
  api_key:
    secure: p/azKPdHhzIcnN+iOmG67ZfA6lp6FjEPE2fhtGlbmEFZ/g03UMfsdBmVDkxEUJ/+UYQtAYAwjTLsTucTmuOx7grumJq3ipyLqnYA3re7wOR/B0x0/WVCPLlteD5CC8lFowSDwgNJZp9+Lrf1fCB7aP9pfIKv2I2Ic1rTjXenqVt0q4HnK+VIPyeLEYi3esli5k1vIXG97ZBsJeuCxm6lEEybKymaArqzbI/neJ35GVrN77thGoeBvvylwyi5413RKanVBMdTEvwQ8LZxP64CwTzKLrGSfAIHeIeKjyJuL9sxmA2+QRSjSeFSnN9Eco2iqeq4VhGKefQjJ5HaZs2L1ElTf3tuHstutdWNaKO0AhywsYXbKhVPW/YSjp4mMoLikdAIuZOq/CBEMSeVpNXP8/wpyMZV+jASl4SNOUnRGgAhobXycfWje/T0cRTuhIoKMvX76wHX4lk0aAP568n35kU03DjJPKlRR0jMds/LPbe+Ig4JO/zHhwMuBMj7bJfMvnyGXFu7H9q/nboZRtyKguaXiRXUfOIqaqaiE0OJQ/KodKXsFCWSOpMPRrNMy6c+LvcKyS1QO2oujs6VFoESWzq9ZYU1l7tPpLO4IlshI4/U7SnXPNUDzPMlI9We9fERcFKDfehT7kOkw+NcUtqEew/0D0cdY26ZObWo8DZSd7c=
  app: 
  run: rails db:migrate
env:
  global:
    secure: rnFIkbyrxraC3x34GiadYwsIlkr/Bj7yq04yylhZty5fXc8P2GOadjL3/xMYDvgGeEqUajeq/Bczhkx4pNRimpybW/QJAdYays3EeCHu6D+JWkDEhYzYUojoMSTB3s9gBEs7tQTe786g+nyv35nVlOKsO8nB7u7xKxbKJeVpf4FAjdZrnFwyemtQC5h2wRU6XS0VbC9DSKaWCjj8nBU7vdQCdMFpIfoEyoPc8U05r/8ONlNHV8GnHW5wE3r14mbjhZHU2gmlrgKjjeOqG5svFX8G3WqZyz0t8uIk6RKIIu3o444fnc8ss5E/V+ekfvnqH4DV90Bs01Cu8X26j8yMA2QRVpbjmql2hfBk++aUSJQzg/F8ZslYqEmh+UrZv2FUSj9KMFAxHcBHwimFERBNVNdBTSRmLQcNBWb1S3s1WabkAQ3HFFU7cuHFd403MLM4KFx+UUq7rNV3U/J3svckYT7At5zt43JENREOks+Pil4xILOcqjHEnDRs9se1dDzIsc7+9lef6lyQI9L2GGXDAqEe5HPedogQ3jV2aAUPlkrHxehEojORsgaNVZYLjh4rT+SwF3yK/b2Ryf2VxTa9VYbkrJyfIMSPm6DaOzTWu4KqewCKKQLK9Du5noTFpqKpGiU3tKfkUCDonWK7Gr9dVKcQwLhK36KUVvbGbE3dFX8=
