language: ruby
rbenv:
- 2.7.2
addons:
  postgresql: 9.6
script:
- bundle exec rails db:{create,migrate} RAILS_ENV=test
- bundle exec rspec
deploy:
  provider: heroku
  api_key:
    secure: vIOWanWm3WMiez43j5D0V4T9pbqukWb+yJ6zAP1YyZBtssJZHUm1S05OK23RO/1yUVFbgZvHlKkiV46a99wIskYQSUcaRVELqM8xM9K+jNpZLM+HvUTplv4JtUHP3wfrsTpnH2R8GWoSlCYn6Ul2xlCltYqFO9yRy1AXlfpxkTyYyYxc6xIO+HXmW427XchIi3rmW1KL3OvnMZiHo8a+kZtgYPAUZtG0YUeHrUXRui3YxWqaBNQkWBnglXbgqgcGN8AlqjByj6ypQ0W3HWrbUio/vWGP7taifG2OKHCJzzBhDkzV3pzFOwczyhCjxaq3cU45QCTXDmNWirsa05vO+/+yEhP0gRp358/HBZKfJQK/UveLjXkj1K1j2/NrdyxReur/IiWyZB1DOJS7U3Yvv4TY4XnykpmaCeFFv48tgGz0shdXMvmEMQW2irNNht/I0BnFAquqfxHTHhDNcfNofkC5cSu7XOIWAHTIz8315jVhVGRQJ4gzJz1q3EXJyceRCKs4Rz+KN87mr4+OyD8E6FMr91EN7FTZK5lMGH9ulTAXtaCwZoBj4aUEqjLuYzIxtcrse66RpYFdWoOrE/acFM3qSHW6khdE8jQ+PTMcjFi+ds1JfwX5sK3X5LsnpNHnGmkMuhF1YM5En11QEwSjcKmD+7Rk9Lop6RJfKVT8mls=
  app: movie-with-friends
  run: rails db:migrate
  on:
    branch: main
env:
  global:
    secure: LzH0nSH77lLZLmWLfzGfPV2CT4qgfu4SKJ6ksYbfLQJdLmaK8JesL36Qw7uEc0G+J5NlOPE62V0hXLeMXoCxKT1EYfaGd0mcV3O0opR7oVXkiCUD5GLVcTQTFPZpnUwRnComH7U4j+wAWMt0yaCloV4orTop71vYFfs4SXSUq5lWS/YRRyCGsJAA9wI2D1UKS4+pFuJsHQs0Q+BCwyL6DkX4YhGSl4j6QIxaQ3Kv3Kg0m88E4zAiAm9gUsIFozLwXbsoz/iWDpzZ6vvDELS+HqVUX5ggDnwkHGTzNRqbLYPthTsBXmoFaGt2TNB2UX60QMoO8eBo/jb4cZgGSv69k8s6Fyzzt3l4OYPNqPfzqZs3wnMZSkdJU5u4xidRL+4yaadXoE28nocN0kDTlOZ31aogiJ45o/u5DQlvSJl/sVJp5uYFT5Buob8AthSuK8FBMpCwKrhLgiNBqfCOONrFp2KcOhR4WZRc6I61CACmFspRyhLFD6IhBKDvHcJcOtBN20HwJ7OAsUX5jPr17FPQPfmLnlq5mu6Tmgn6t4VQD321j9delOkRNmh6RA1MklC45n2l4YOpg2rXzNGfMSh6QMeY5LqnOFaUGuyTdpdzLNL01ClslzhGGUWcfXlUeQutWq/qC8WrSU42aCKor5R2eeGKff00Wr40D1QFhwIbFC0=
