language: ruby
rbenv:
- 2.7.2
addons:
  postgresql: 9.6
script:
- bundle exec rails db:{create,migrate} RAILS_ENV=test
- bundle exec rspec
deploy:
  provider: heroku
  api_key:
    secure: vIOWanWm3WMiez43j5D0V4T9pbqukWb+yJ6zAP1YyZBtssJZHUm1S05OK23RO/1yUVFbgZvHlKkiV46a99wIskYQSUcaRVELqM8xM9K+jNpZLM+HvUTplv4JtUHP3wfrsTpnH2R8GWoSlCYn6Ul2xlCltYqFO9yRy1AXlfpxkTyYyYxc6xIO+HXmW427XchIi3rmW1KL3OvnMZiHo8a+kZtgYPAUZtG0YUeHrUXRui3YxWqaBNQkWBnglXbgqgcGN8AlqjByj6ypQ0W3HWrbUio/vWGP7taifG2OKHCJzzBhDkzV3pzFOwczyhCjxaq3cU45QCTXDmNWirsa05vO+/+yEhP0gRp358/HBZKfJQK/UveLjXkj1K1j2/NrdyxReur/IiWyZB1DOJS7U3Yvv4TY4XnykpmaCeFFv48tgGz0shdXMvmEMQW2irNNht/I0BnFAquqfxHTHhDNcfNofkC5cSu7XOIWAHTIz8315jVhVGRQJ4gzJz1q3EXJyceRCKs4Rz+KN87mr4+OyD8E6FMr91EN7FTZK5lMGH9ulTAXtaCwZoBj4aUEqjLuYzIxtcrse66RpYFdWoOrE/acFM3qSHW6khdE8jQ+PTMcjFi+ds1JfwX5sK3X5LsnpNHnGmkMuhF1YM5En11QEwSjcKmD+7Rk9Lop6RJfKVT8mls=
  app: movie-with-friends
  run: rails db:migrate
  on:
    branch: main
env:
  global:
    secure: rnFIkbyrxraC3x34GiadYwsIlkr/Bj7yq04yylhZty5fXc8P2GOadjL3/xMYDvgGeEqUajeq/Bczhkx4pNRimpybW/QJAdYays3EeCHu6D+JWkDEhYzYUojoMSTB3s9gBEs7tQTe786g+nyv35nVlOKsO8nB7u7xKxbKJeVpf4FAjdZrnFwyemtQC5h2wRU6XS0VbC9DSKaWCjj8nBU7vdQCdMFpIfoEyoPc8U05r/8ONlNHV8GnHW5wE3r14mbjhZHU2gmlrgKjjeOqG5svFX8G3WqZyz0t8uIk6RKIIu3o444fnc8ss5E/V+ekfvnqH4DV90Bs01Cu8X26j8yMA2QRVpbjmql2hfBk++aUSJQzg/F8ZslYqEmh+UrZv2FUSj9KMFAxHcBHwimFERBNVNdBTSRmLQcNBWb1S3s1WabkAQ3HFFU7cuHFd403MLM4KFx+UUq7rNV3U/J3svckYT7At5zt43JENREOks+Pil4xILOcqjHEnDRs9se1dDzIsc7+9lef6lyQI9L2GGXDAqEe5HPedogQ3jV2aAUPlkrHxehEojORsgaNVZYLjh4rT+SwF3yK/b2Ryf2VxTa9VYbkrJyfIMSPm6DaOzTWu4KqewCKKQLK9Du5noTFpqKpGiU3tKfkUCDonWK7Gr9dVKcQwLhK36KUVvbGbE3dFX8=
