language: ruby
rbenv:
- 2.7.2
addons:
  postgresql: 9.6
script:
- bundle exec rails db:{create,migrate} RAILS_ENV=test
- bundle exec rspec
deploy:
  provider: heroku
  api_key:
    secure: MqCxGjEWpmD/qUp1Rb5PE/1MwdZRh24D1uCpG0V5VGo8xdgBzK7w1N7CmwhPw009SJkqDWvk5HvkZcoqlM/L0jlc7acfZCVYuXsY56otftZTrucasKOrYioLeOScLidJvKftmR/VLOmcsXACvCtnCTwqwPUFxwLRrMy7yggL9zkJJJhcU2snWVoWSlczARaERbbnyFrkGIe33B8S1ZmiK9dLp4h7+vbv+m4W0wcZcLsBmneBD1KJ0RBBFtKeHkufzQ1/y9kyDQPRlnVlyRlUpJFWp9Q6x4UOmIPKSSj/veScjicphYKHY/j5kEgt/o5NZlPJbxkkT65v2NnutG/GWODk4eDs9s7gQ3NJEBRNe6tHQmNN9voBK5l3sfMuZ0hkFkrff8i94/8Lr6dOVDXf1P6C1u7P60+Ifeb874erztjNADJsUlZAMDuvaw3HlbZ6VDu5riN9fD2dMbFf0hxN3IeKm7G6m01+ofO7u1YipyYUyvZvDtcZtBPkrw73zl9+RdEaVk6xrao1ZdqbrGTCEaIxzOwKV+swmNWbrZb+a9hX2zaoUCPkeax+tkWZVjPEXfi2A4chOhDCOXqBs3L0sdwtL2R+b08Dp9m07ZMibaeUlzoC42CZi9sItbmDG2YU/CZ/+APDvRK9tdNYfmd6tGSXxJopwvTeT1SNSasY+0o=
  app: 
  run: rails db:migrate
env:
  global:
    secure: rnFIkbyrxraC3x34GiadYwsIlkr/Bj7yq04yylhZty5fXc8P2GOadjL3/xMYDvgGeEqUajeq/Bczhkx4pNRimpybW/QJAdYays3EeCHu6D+JWkDEhYzYUojoMSTB3s9gBEs7tQTe786g+nyv35nVlOKsO8nB7u7xKxbKJeVpf4FAjdZrnFwyemtQC5h2wRU6XS0VbC9DSKaWCjj8nBU7vdQCdMFpIfoEyoPc8U05r/8ONlNHV8GnHW5wE3r14mbjhZHU2gmlrgKjjeOqG5svFX8G3WqZyz0t8uIk6RKIIu3o444fnc8ss5E/V+ekfvnqH4DV90Bs01Cu8X26j8yMA2QRVpbjmql2hfBk++aUSJQzg/F8ZslYqEmh+UrZv2FUSj9KMFAxHcBHwimFERBNVNdBTSRmLQcNBWb1S3s1WabkAQ3HFFU7cuHFd403MLM4KFx+UUq7rNV3U/J3svckYT7At5zt43JENREOks+Pil4xILOcqjHEnDRs9se1dDzIsc7+9lef6lyQI9L2GGXDAqEe5HPedogQ3jV2aAUPlkrHxehEojORsgaNVZYLjh4rT+SwF3yK/b2Ryf2VxTa9VYbkrJyfIMSPm6DaOzTWu4KqewCKKQLK9Du5noTFpqKpGiU3tKfkUCDonWK7Gr9dVKcQwLhK36KUVvbGbE3dFX8=
