language: ruby
rbenv:
- 2.7.2
addons:
  postgresql: 9.6
script:
- bundle exec rails db:{create,migrate} RAILS_ENV=test
- bundle exec rspec
deploy:
  provider: heroku
  api_key:
    secure: Pa4iOWSJXQaXQyqczRszfjTqVx8SqMUsp5jP7wPpceDB5cgovoM3XyC3HN5OYLjnKKp0bwBlKWLc/K54Q1G5eZM6/Mvndxy7Pdi6AqplMmac/xSrWS/Hj93KbYEjMJJhzMEofsgAWy0GBncpL9MDN6Z3VJqtHzRzT+wIDM8uVPP0maxurHdQMsIDRAnZshNO/zJuUZdF3k9RBPM4PfIJuBao5padVT8db9HfqLwWj13IjZcMhw0FVXjiZ2FYK8nt3bLF8t1SQoFFXiUULM+Aw+g0+uErqirNmDgRNjj4u5SzFsNvEQHr3VsGkQYhlgMoXe0T4qe/sJzGE3gGWF46/BE4vXLHxbBLsB3KjskYM0404+2iCO4i+vynSxRq8OYGgaUBJZChbtPIHzQDhs9UY4Y/ipioELwcyGd/NUOYpj2lcHc+zS42ZEScSYUo8STeVd5PxBJxHvwtZdYHiEQvnma61m1oK70m8jmRPKrITMSyWWPh41FPBAxocBsheUvu6cJ1AMvWtHTx2X76ghJzCb+LUgIzCFJTCxR8DvKwTPpBjbf95xCavIjpLecDtPATaRNRSCDuFucX04Y7PqXhvQNVvMHttuHXha8PDYU9lyfi7zw/t2yGd5Emo/8lS47bg6TLOliZepM2gCojEeSE09utum/C8xlMLfN9B8/K8BY=
  app: 
  run: rails db:migrate
env:
  global:
    secure: rnFIkbyrxraC3x34GiadYwsIlkr/Bj7yq04yylhZty5fXc8P2GOadjL3/xMYDvgGeEqUajeq/Bczhkx4pNRimpybW/QJAdYays3EeCHu6D+JWkDEhYzYUojoMSTB3s9gBEs7tQTe786g+nyv35nVlOKsO8nB7u7xKxbKJeVpf4FAjdZrnFwyemtQC5h2wRU6XS0VbC9DSKaWCjj8nBU7vdQCdMFpIfoEyoPc8U05r/8ONlNHV8GnHW5wE3r14mbjhZHU2gmlrgKjjeOqG5svFX8G3WqZyz0t8uIk6RKIIu3o444fnc8ss5E/V+ekfvnqH4DV90Bs01Cu8X26j8yMA2QRVpbjmql2hfBk++aUSJQzg/F8ZslYqEmh+UrZv2FUSj9KMFAxHcBHwimFERBNVNdBTSRmLQcNBWb1S3s1WabkAQ3HFFU7cuHFd403MLM4KFx+UUq7rNV3U/J3svckYT7At5zt43JENREOks+Pil4xILOcqjHEnDRs9se1dDzIsc7+9lef6lyQI9L2GGXDAqEe5HPedogQ3jV2aAUPlkrHxehEojORsgaNVZYLjh4rT+SwF3yK/b2Ryf2VxTa9VYbkrJyfIMSPm6DaOzTWu4KqewCKKQLK9Du5noTFpqKpGiU3tKfkUCDonWK7Gr9dVKcQwLhK36KUVvbGbE3dFX8=
